//import "windows.foundation.idl";
import "forwards.idl";
import "output.idl";

namespace Org
{
    namespace WebRtc
    {


        [version(1.0)]
        [uuid(5383522e-090b-ef6c-b517-30a29261535f)]
        interface IAudioData : IInspectable
        {

            /// <summary>
            /// Gets if the data is read-only.
            /// </summary>
            Boolean ReadOnly { get; };

            /// <summary>
            /// Gets or sets the audio samples data.
            /// </summary>
            Windows.Foundation.Collections.IVectorView< Int16 > Data { get; set; };
        };

        runtimeclass AudioData : [default] IAudioData, Windows.Foundation.IClosable
        {

            /// <summary>
            /// Constructs a new audio data object.
            /// </summary>
            [default_overload]
            AudioData();

            /// <summary>
            /// Cast from Org.WebRtc.IAudioData to Org.WebRtc.AudioData
            /// </summary>
            [default_overload]
            [method_name("CastFromIAudioData")]
            static Org.WebRtc.AudioData Cast(Org.WebRtc.IAudioData source);
        };

    } // namespace WebRtc
} // namespace Org

