//import "windows.foundation.idl";
import "forwards.idl";
import "output.idl";

namespace Org
{
    namespace WebRtc
    {


        /// <summary>
        /// MediaSample represents an object holder for a platform specific
        /// media sample.
        /// </summary>
        [version(1.0)]
        [uuid(874bd3d1-9a59-41cf-b1f9-d4018e84e64c)]
        interface IMediaSample : IInspectable
        {

          /// <summary>
          /// Returns camera view transform which maps from the coordinate
          /// system to the camera.
          /// </summary>
          Windows.Foundation.Collections.IVectorView< Single > GetCameraViewTransform();

          /// <summary>
          /// Returns camera projection transform which maps from the camera
          /// to pixels in the image.
          /// </summary>
          Windows.Foundation.Collections.IVectorView< Single > GetCameraProjectionTransform();
      };

        /// <summary>
        /// MediaSample represents an object holder for a platform specific
        /// media sample.
        /// </summary>
        runtimeclass MediaSample : [default] IMediaSample
        {

            /// <summary>
            /// Cast from Org.WebRtc.IMediaSample to Org.WebRtc.MediaSample
            /// </summary>
            [default_overload]
            [method_name("CastFromIMediaSample")]
            static Org.WebRtc.MediaSample Cast(Org.WebRtc.IMediaSample source);
        };

    } // namespace WebRtc
} // namespace Org

