// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webRtc_AudioData.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webRtc {

        struct AudioData : public wrapper::org::webRtc::AudioData
        {
          ZS_DECLARE_TYPEDEF_PTR(wrapper::org::webRtc::AudioData, WrapperType);
          ZS_DECLARE_TYPEDEF_PTR(wrapper::impl::org::webRtc::AudioData, WrapperImplType);
          AudioDataWeakPtr thisWeak_;

          AudioData() noexcept;
          virtual ~AudioData() noexcept;


          // methods AudioData
          void wrapper_init_org_webRtc_AudioData() noexcept override;

          // properties AudioData
          bool get_readOnly() noexcept override;
          shared_ptr< list< int16_t > > get_data() noexcept override;
          void set_data(shared_ptr< list< int16_t > > value) noexcept override;
        };

      } // webRtc
    } // org
  } // namespace impl
} // namespace wrapper

