// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webRtc_VideoOptions.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webRtc {

        struct VideoOptions : public wrapper::org::webRtc::VideoOptions
        {
          ZS_DECLARE_TYPEDEF_PTR(wrapper::org::webRtc::VideoOptions, WrapperType);
          ZS_DECLARE_TYPEDEF_PTR(wrapper::impl::org::webRtc::VideoOptions, WrapperImplType);
          VideoOptionsWeakPtr thisWeak_;

          VideoOptions() noexcept;
          virtual ~VideoOptions() noexcept;

          void wrapper_init_org_webRtc_VideoOptions() noexcept override;
        };

      } // webRtc
    } // org
  } // namespace impl
} // namespace wrapper

