// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webRtc_AudioFrame.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webRtc {

        struct AudioFrame : public wrapper::org::webRtc::AudioFrame
        {
          ZS_DECLARE_TYPEDEF_PTR(wrapper::org::webRtc::AudioFrame, WrapperType);
          ZS_DECLARE_TYPEDEF_PTR(wrapper::impl::org::webRtc::AudioFrame, WrapperImplType);
          AudioFrameWeakPtr thisWeak_;

          AudioFrame() noexcept;
          virtual ~AudioFrame() noexcept;


          // methods AudioFrame
          void wrapper_init_org_webRtc_AudioFrame() noexcept override;
        };

      } // webRtc
    } // org
  } // namespace impl
} // namespace wrapper

