// Generated by zsLibEventingTool

#include "impl_org_webRtc_AudioData.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

// borrow definitions from class
ZS_DECLARE_TYPEDEF_PTR(wrapper::impl::org::webRtc::AudioData::WrapperImplType, WrapperImplType);
ZS_DECLARE_TYPEDEF_PTR(WrapperImplType::WrapperType, WrapperType);

//------------------------------------------------------------------------------
wrapper::impl::org::webRtc::AudioData::AudioData() noexcept
{
}

//------------------------------------------------------------------------------
wrapper::org::webRtc::AudioDataPtr wrapper::org::webRtc::AudioData::wrapper_create() noexcept
{
  auto pThis = make_shared<wrapper::impl::org::webRtc::AudioData>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::webRtc::AudioData::~AudioData() noexcept
{
  thisWeak_.reset();
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webRtc::AudioData::wrapper_init_org_webRtc_AudioData() noexcept
{
}

//------------------------------------------------------------------------------
bool wrapper::impl::org::webRtc::AudioData::get_readOnly() noexcept
{
  bool result {};
  return result;
}

//------------------------------------------------------------------------------
shared_ptr< list< int16_t > > wrapper::impl::org::webRtc::AudioData::get_data() noexcept
{
  shared_ptr< list< int16_t > > result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webRtc::AudioData::set_data(shared_ptr< list< int16_t > > value) noexcept
{
}


