// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webRtc_AudioBufferConfiguration.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webRtc {

        struct AudioBufferConfiguration : public wrapper::org::webRtc::AudioBufferConfiguration
        {
          ZS_DECLARE_TYPEDEF_PTR(wrapper::org::webRtc::AudioBufferConfiguration, WrapperType);
          ZS_DECLARE_TYPEDEF_PTR(wrapper::impl::org::webRtc::AudioBufferConfiguration, WrapperImplType);
          AudioBufferConfigurationWeakPtr thisWeak_;

          AudioBufferConfiguration() noexcept;
          virtual ~AudioBufferConfiguration() noexcept;

          void wrapper_init_org_webRtc_AudioBufferConfiguration() noexcept override;
        };

      } // webRtc
    } // org
  } // namespace impl
} // namespace wrapper

