// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webRtc_AudioBufferEvent.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webRtc {

        struct AudioBufferEvent : public wrapper::org::webRtc::AudioBufferEvent
        {
          ZS_DECLARE_TYPEDEF_PTR(wrapper::org::webRtc::AudioBufferEvent, WrapperType);
          ZS_DECLARE_TYPEDEF_PTR(wrapper::impl::org::webRtc::AudioBufferEvent, WrapperImplType);
          AudioBufferEventWeakPtr thisWeak_;

          AudioBufferEvent() noexcept;
          virtual ~AudioBufferEvent() noexcept;
          void wrapper_dispose() noexcept override;


          // properties AudioBufferEvent
          wrapper::org::webRtc::AudioBufferPtr get_buffer() noexcept override;
        };

      } // webRtc
    } // org
  } // namespace impl
} // namespace wrapper

